version: "3"
services:
  redis-master-1:
    platform: linux/x86_64
    image: redis:7
    container_name: redis-master-1
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./conf/redis-master-1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 7006:7006

  redis-master-2:
    network_mode: "service:redis-master-1"
    platform: linux/x86_64
    image: redis:7
    container_name: redis-master-2
    volumes:
      - ./conf/redis-master-2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-master-3:
    network_mode: "service:redis-master-1"
    platform: linux/x86_64
    image: redis:7
    container_name: redis-master-3
    volumes:
      - ./conf/redis-master-3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-replica-4:
    network_mode: "service:redis-master-1"
    platform: linux/x86_64
    image: redis:7
    container_name: redis-replica-4
    volumes:
      - ./conf/redis-replica-4.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-replica-5:
    network_mode: "service:redis-master-1"
    platform: linux/x86_64
    image: redis:7
    container_name: redis-replica-5
    volumes:
      - ./conf/redis-replica-5.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-replica-6:
    network_mode: "service:redis-master-1"
    platform: linux/x86_64
    image: redis:7
    container_name: redis-replica-6
    volumes:
      - ./conf/redis-replica-6.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-clustering-helper:
    network_mode: "service:redis-master-1" # Configure the created redis nodes to use this network
    platform: linux/x86_64
    image: redis:7
    container_name: redis-clustering-helper
    entrypoint: ["sh", "-c"]
    command:
    - |
      sleep 3 &&
      redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-yes --cluster-replicas 1
      echo "Clustered. please remove helper container"
    depends_on: # After redis-node-1, ..., redis-replica-6 are created, redis-node-entry can be created
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-replica-4
      - redis-replica-5
      - redis-replica-6
